name: Lottery
main: net.erbros.Lottery.Lottery
version: 0.5.0
author: Erbros
website: www.erbros.net
commands:
  lottery:
    description: Provides access to Permissions commands and information.
    permission: lottery.buy
    usage: |
           /<command>
           Example: /<command> | Displays Permissions Info
           Example: /<command> -reload all | Reloads the default world configuration
           Example: /<command> -reload [world] | Reloads the [world] configuration file